apiVersion: v1
kind: Namespace
metadata:
  name: crypto-k8
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: crypto-recommendation-config
  namespace: crypto-k8
  labels:
    app: crypto-recommendation-pod
data:
  PSQL_DB_URL: ${PSQL_DB_URL}
  PSQL_DB_USR: ${PSQL_DB_USR}
  PSQL_DB_PWD: ${PSQL_DB_PWD}
---
apiVersion: v1
kind: Service
metadata:
  name: crypto-recommendation
  namespace: crypto-k8
spec:
  type: LoadBalancer
  selector:
    app: crypto-recommendation-pod
  ports:
    - protocol: "TCP"
      port: 8080
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: crypto-recommendation
  namespace: crypto-k8
spec:
  selector:
    matchLabels:
      app: crypto-recommendation-pod
  replicas: 1
  template:
    metadata:
      labels:
        app: crypto-recommendation-pod
        owner: epamzurabtikaradze
    spec:
      containers:
        - name: crypto-recommendation
          image: epamzurabtikaradze/crypto-recommendation-service:1.0.0
          envFrom:
            - configMapRef:
                name: crypto-recommendation-config
          ports:
            - containerPort: 8080